name: Test workflow

on:
  push:
    
jobs:
  echo-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependancies
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Build
        run: npm run build
  